name: HologramBridge
version: ${project.version}
main: gg.optimalgames.hologrambridge.HologramBridgePlugin
api-version: 1.19
authors: [Chubbyduck1]
description: A bridge between Hologram plugins
softdepend: [HolographicDisplays, CMI, Holograms, DecentHolograms, FancyHolograms]
